language: cpp
compiler:
  - gcc
  - clang
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#shogun"
    on_success: change
    on_failure: always
    template:
      - "it's %{author}'s turn to pay the next round of drinks for the massacre he caused in %{repository}: %{build_url}"
matrix:
  include:
    - compiler: clang
      python: 2.7
      language: python
      env: CMAKE_OPTIONS="-DPythonModular=ON" EXTRA_PACKAGES="python-scipy swig2.0" CC=clang CXX=clang++
    - compiler: clang
      python: 3.3
      language: python
      env: CMAKE_OPTIONS="-DPythonModular=ON" EXTRA_PACKAGES="python3-scipy swig2.0" CC=clang CXX=clang++
    - compiler: clang
      rvm: 1.8.7
      language: ruby
      env: CMAKE_OPTIONS="-DRubyModular=ON" CUSTOM_PKG="gem install narray" EXTRA_PACKAGES="swig2.0" CC=clang CXX=clang++
    - compiler: clang
      jdk: oraclejdk7
      language: java
      env: CMAKE_OPTIONS="-DJavaModular=ON" EXTRA_PACKAGES="jblas swig2.0" CC=clang CXX=clang++
    - compiler: clang
      env: CMAKE_OPTIONS="-DCSharpModular=ON" EXTRA_PACKAGES="mono-devel mono-gmcs cli-common-dev swig2.0" CC=clang CXX=clang++
    - compiler: clang
      env: CMAKE_OPTIONS="-DLuaModular=ON" EXTRA_PACKAGES="lua5.1 liblua5.1-0-dev swig2.0" CC=clang CXX=clang++
    - compiler: gcc
      env: CMAKE_OPTIONS="-DOctaveModular=ON" EXTRA_PACKAGES="octave octave3.2-headers swig2.0"
    - compiler: clang
      env: CMAKE_OPTIONS="-DRModular=ON" EXTRA_PACKAGES="r-base-core swig2.0" CC=clang CXX=clang++
  allow_failures:
    - compiler: clang
      env: CMAKE_OPTIONS="-DRModular=ON" EXTRA_PACKAGES="r-base-core swig2.0"
    - compiler: clang
      python: 3.3
      language: python
      env: CMAKE_OPTIONS="-DPythonModular=ON" EXTRA_PACKAGES="python3-scipy swig2.0"
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libbz2-dev cdbs libarpack2-dev libatlas-base-dev libblas-dev libglpk-dev libhdf5-serial-dev zlib1g-dev libxml2-dev libreadline6-dev libreadline-dev libsnappy-dev liblzo2-dev liblzma-dev liblapack-dev gdb cmake python-jinja2 $EXTRA_PACKAGES
 - $CUSTOM_PKG
before_script: 
  - mkdir build
  - cd build
script: cmake -DENABLE_TESTING=ON -DBUNDLE_EIGEN=ON -DBUNDLE_JSON=ON $CMAKE_OPTIONS .. && make -j 4 && sudo make install && ctest --output-on-failure
