language: cpp
compiler:
  - gcc
branches:
  only:
    - master
notifications:
  recipients:
    - wiking@jol.hu
  email:
    on_success: change
    on_failure: alwaye
before_install:
 - sudo apt-get update -qq
 - sudo apt-get build-dep -qq shogun
 - sudo apt-get install -qq libeigen3-dev
before_script: cd ./src
script: ./configure --interfaces=python_modular,r_modular && make -j 4 && make tests
