language: cpp
compiler:
  - gcc
  - clang
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#shogun"
    on_success: change
    on_failure: always
    template:
      - "it's %{author}'s turn to pay the next round of drinks for the massacre he caused in %{repository}: %{build_url}"
env:
 - INTERFACES="" EXTRA_PACKAGES=""
 - INTERFACES=python_static EXTRA_PACKAGES="python-numpy-dev python-dev"
 - INTERFACES=python_modular EXTRA_PACKAGES="python-numpy-dev python-dev swig2.0"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cdbs libeigen3-dev libarpack2-dev libatlas-base-dev libblas-dev libglpk-dev libhdf5-serial-dev libjson0-dev swig zlib1g-dev libxml2-dev libreadline6-dev libreadline-dev libsnappy-dev liblzo2-dev liblzma-dev liblapack-dev gdb $EXTRA_PACKAGES
before_script: cd ./src
script: ./configure --disable-optimization --interfaces=$INTERFACES && make -j 4 && sudo make install && make tests
