jobs:
- job: lint
  displayName: Check code formatting
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: ubuntu-16.04

  variables:
    testRunTitle: '$(build.sourceBranchName)-debian'
    testRunPlatform: debian
    imageName: 'shogun/shogun-dev'

  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
    submodules: true

  - task: docker@0
    displayName: Lint
    inputs:
      action: 'Run an image'
      imageName: $(imageName)
      volumes: |
        $(build.sourcesDirectory):/src
      workDir: '/src'
      containerCommand: './scripts/check_format.sh $(System.PullRequest.SourceBranch) $(System.PullRequest.TargetBranch)'

- job: libshogun
  displayName: Linux libshogun
  timeoutInMinutes: 90

  pool:
    vmImage: ubuntu-16.04

  strategy:
    maxParallel: 2
    matrix:
      clang:
        CC: "clang"
        CXX: "clang++"
        cmakeOptions: '-G "Ninja" -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DDISABLE_META_INTEGRATION_TESTS=ON'
      gcc:
        CC: "gcc"
        CXX: "g++"
        cmakeOptions: '-G "Ninja" -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DDISABLE_META_INTEGRATION_TESTS=ON'

  variables:
    testRunTitle: '$(build.sourceBranchName)-debian'
    testRunPlatform: debian
    imageName: 'shogun/shogun-dev'
    targetPrefix: '$(build.binariesDirectory)/opt'
    libshogunArtifactName: 'libshogun-$(CC)'
    libshogunArchive: '$(Build.ArtifactStagingDirectory)/libshogun-$(Build.BuildId).tar'
    ccacheDir: '$(build.binariesDirectory)/ccache'
    ccacheArtifactName: 'ccache-$(CC)'
    ccacheArchive: '$(Build.ArtifactStagingDirectory)/ccache-$(Build.BuildId).tar'

  steps:
  - template: ./docker-steps.yml

- job: macOS
  displayName: MacOS
  timeoutInMinutes: 90

  variables:
    testRunTitle: '$(build.sourceBranchName)-macos'
    testRunPlatform: macos
    ccacheDir: '$(build.binariesDirectory)/ccache'
    ccacheArtifactName: 'ccache-macos'
    ccacheArchive: '$(Build.ArtifactStagingDirectory)/ccache-$(Build.BuildId).tar'
    commonMacOSCMakeFlags: '-DBUILD_EXAMPLES=OFF -DBUNDLE_NLOPT=OFF -DDISABLE_META_INTEGRATION_TESTS=ON -DENABLE_TESTING=ON -DENABLE_COVERAGE=OFF -DBUILD_META_EXAMPLES=OFF'
    openMPMacOSCMakeFlags:
      '-DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp"
      -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp"
      -DOpenMP_CXX_LIB_NAMES="omp" -DOpenMP_C_LIB_NAMES="omp"
      -DOpenMP_omp_LIBRARY="/usr/local/opt/libomp/lib/libomp.dylib"'

  pool:
    vmImage: macOS-10.14

  steps:
  - template: ./macos-steps.yml

  strategy:
    maxParallel: 2
    matrix:
      ACCELERATE:
        use_mkl: false
        cmakeOptions: '$(commonMacOSCMakeFlags)'
      MKL:
        use_mkl: true
        cmakeOptions: '$(commonMacOSCMakeFlags) $(openMPMacOSCMakeFlags) -DBLAS_LIBRARIES=$(CONDA)/lib/libmkl_core.dylib -DLAPACK_LIBRARIES=$(CONDA)/lib/libmkl_core.dylib -DBLA_VENDOR=Intel'

- job: windows_libshogun
  displayName: Windows
  timeoutInMinutes: 180

  pool:
    vmImage: 'windows-latest'

  strategy:
    matrix:
      py36:
        CONDA_PY: "36"
        CONDA_ENV: shogun
        cmakeOptions: '-DBUILD_META_EXAMPLES=OFF -DDISABLE_META_INTEGRATION_TESTS=ON'

  variables:
    clcacheDir: 'C:\\Users\\VssAdministrator\\clcache'
    clcacheArtifactName: 'clcache-vs17'
    clcacheArchive: '$(Build.ArtifactStagingDirectory)/clcache-$(Build.BuildId).tar.gz'
    libshogunArtifactName: 'libshogun-vs17'
    libshogunArchive: '$(Build.ArtifactStagingDirectory)/libshogun-$(Build.BuildId).tar.gz'
    targetPrefix: '$(Build.BinariesDirectory)\\opt'
    buildConfiguration: Release
    buildPlatform: x64

  steps:
  - template: ./windows-steps.yml
